general.import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"  
]

[window]
dynamic_padding = true
decorations = "None"
padding = { x = 8, y = 8 }

[terminal]
shell = "/usr/bin/fish"

[font]
size = 10

[font.normal]
family = "Cascadia Code"
